const LONG_VALUE = "0123456789".repeat(1200)

export const LARGE_MESSAGE = {
  Time: new Date().toISOString(),
  Computer: "Computer2",
  "OperationId": "12345",
  "OrderId": "54321",
  "Amount": "10.00",
  AdditionalContext: {
    "InstanceName": LONG_VALUE,
    "TimeZone": LONG_VALUE,
    "Level": 4,
    "CounterName": LONG_VALUE,
    "CounterValue": 43.5,
    value1_2: LONG_VALUE,
    value: {
      value: {
        value1_1: LONG_VALUE,
        value: {
          test: "one",
          value1_3: LONG_VALUE,
          value: {
            value1_4: LONG_VALUE,
            value: {
              value1_5: LONG_VALUE,
              value: {
                value1_6: LONG_VALUE,
                value1_7: LONG_VALUE,
                value1_8: LONG_VALUE,
                value1_9: LONG_VALUE,
                value2_1: LONG_VALUE,
                value2_2: LONG_VALUE,
                value2_3: LONG_VALUE,
                value2_4: LONG_VALUE,
                value2_5: LONG_VALUE,
                value2_6: LONG_VALUE,
                value2_7: LONG_VALUE,
                value2_8: LONG_VALUE,
                value2_9: LONG_VALUE,
                value3_1: LONG_VALUE,
                value3_2: LONG_VALUE,
                value3_3: LONG_VALUE,
                value3_4: LONG_VALUE,
                value3_5: LONG_VALUE,
                value3_6: LONG_VALUE,
                value3_7: LONG_VALUE,
                value3_8: LONG_VALUE,
                value3_9: LONG_VALUE,
                value4_1: LONG_VALUE,
                value4_2: LONG_VALUE,
                value4_3: LONG_VALUE,
                value4_4: LONG_VALUE,
                value4_5: LONG_VALUE,
                value4_6: LONG_VALUE,
                value4_7: LONG_VALUE,
                value4_8: LONG_VALUE,
                value4_9: LONG_VALUE,
                value5_1: LONG_VALUE,
                value5_2: LONG_VALUE,
                value5_3: LONG_VALUE,
                value5_4: LONG_VALUE,
                value5_5: LONG_VALUE,
                value5_6: LONG_VALUE,
                value5_7: LONG_VALUE,
                value5_8: LONG_VALUE,
                value5_9: LONG_VALUE,
                value1_1_2: LONG_VALUE,
                value1_1_1: LONG_VALUE,
                value1_1_3: LONG_VALUE,
                value1_1_4: LONG_VALUE,
                value1_1_5: LONG_VALUE,
                value1_1_6: LONG_VALUE,
                value1_1_7: LONG_VALUE,
                value1_1_8: LONG_VALUE,
                value1_1_9: LONG_VALUE,
                value1_2_1: LONG_VALUE,
                value1_2_2: LONG_VALUE,
                value1_2_3: LONG_VALUE,
                value1_2_4: LONG_VALUE,
                value1_2_5: LONG_VALUE,
                value1_2_6: LONG_VALUE,
                value1_2_7: LONG_VALUE,
                value1_2_8: LONG_VALUE,
                value1_2_9: LONG_VALUE,
                value1_3_1: LONG_VALUE,
                value1_3_2: LONG_VALUE,
                value1_3_3: LONG_VALUE,
                value1_3_4: LONG_VALUE,
                value1_3_5: LONG_VALUE,
                value1_3_6: LONG_VALUE,
              }
            }
          }
        }
      }
    }
  }
}

const MEDIUM_VALUE = "0123456789".repeat(100)

export const MEDIUM_MESSAGE = {
  severityNumber: 1,
  other: "value",
  body: "This is a log message",

  // https://learn.microsoft.com/en-us/azure/azure-monitor/app/data-model-complete
  OperationId: "OperationId",
  operation_Id: "operation_Id",
  OperationName: "OperationName",
  operation_Name: "operation_Name",
  TraceId: "TraceId",
  trace_id: "trace_id",
  traceId: "traceId",
  spanId: "spanId",
  attributes: {
    OperationId: "AttrOperationId",
    operation_Id: "Attroperation_Id",
    OperationName: "AttrOperationName",
    operation_Name: "Attroperation_Name",
    TraceId: "AttrTraceId",
    trace_id: "Attrtrace_id",
    traceId: "AttrtraceId",
    spanId: "spanId",
    value1_1: MEDIUM_VALUE,
    value1_2: MEDIUM_VALUE,
    value1_3: MEDIUM_VALUE,
    value1_4: MEDIUM_VALUE,
    value1_5: MEDIUM_VALUE,
    value1_6: MEDIUM_VALUE,
    value1_7: MEDIUM_VALUE,
    value1_8: MEDIUM_VALUE,
    value1_9: MEDIUM_VALUE,
    value2_1: MEDIUM_VALUE,
    value2_2: MEDIUM_VALUE,
    value2_3: MEDIUM_VALUE,
    value2_4: MEDIUM_VALUE,
    value2_5: MEDIUM_VALUE,
    value2_6: MEDIUM_VALUE,
    value2_7: MEDIUM_VALUE,
    value2_8: MEDIUM_VALUE,
    value2_9: MEDIUM_VALUE,
    value3_1: MEDIUM_VALUE,
    value3_2: MEDIUM_VALUE,
    value3_3: MEDIUM_VALUE,
    value3_4: MEDIUM_VALUE,
    value3_5: MEDIUM_VALUE,
    value3_6: MEDIUM_VALUE,
    value3_7: MEDIUM_VALUE,
    value3_8: MEDIUM_VALUE,
    value3_9: MEDIUM_VALUE,
    value4_1: MEDIUM_VALUE,
    value4_2: MEDIUM_VALUE,
    value4_3: MEDIUM_VALUE,
    value4_4: MEDIUM_VALUE,
    value4_5: MEDIUM_VALUE,
    value4_6: MEDIUM_VALUE,
    value4_7: MEDIUM_VALUE,
    value4_8: MEDIUM_VALUE,
    value4_9: MEDIUM_VALUE,
    value5_1: MEDIUM_VALUE,
    value5_2: MEDIUM_VALUE,
    value5_3: MEDIUM_VALUE,
    value5_4: MEDIUM_VALUE,
    value5_5: MEDIUM_VALUE,
    value5_6: MEDIUM_VALUE,
    value5_7: MEDIUM_VALUE,
    value5_8: MEDIUM_VALUE,
    value5_9: MEDIUM_VALUE,
  },
}

export const MEDIUM_MESSAGE_NESTED = {
  severityNumber: 1,
  other: "value",
  body: "This is medium nested log message",

  // https://learn.microsoft.com/en-us/azure/azure-monitor/app/data-model-complete
  OperationId: "OperationId",
  operation_Id: "operation_Id",
  OperationName: "OperationName",
  operation_Name: "operation_Name",
  TraceId: "TraceId",
  trace_id: "trace_id",
  traceId: "traceId",
  spanId: "spanId",
  attributes: {
    value1_1: {
      MEDIUM_VALUE,
      value1_1_2: {
        MEDIUM_VALUE,
      },
      value1_2: MEDIUM_VALUE,
      value1_3: MEDIUM_VALUE,
      value1_4: MEDIUM_VALUE,
      value1_5: MEDIUM_VALUE,
      value1_6: MEDIUM_VALUE,
      value1_7: MEDIUM_VALUE,
      value1_8: MEDIUM_VALUE,
      value1_9: MEDIUM_VALUE,
      value2_1: MEDIUM_VALUE,
      value2_2: MEDIUM_VALUE,
      value2_3: MEDIUM_VALUE,
      value2_4: MEDIUM_VALUE,
      value2_5: MEDIUM_VALUE,
      value2_6: MEDIUM_VALUE,
      value2_7: MEDIUM_VALUE,
      value2_8: MEDIUM_VALUE,
      value2_9: MEDIUM_VALUE,
      value3_1: MEDIUM_VALUE,
      value3_2: MEDIUM_VALUE,
      value3_3: MEDIUM_VALUE,
      value3_4: MEDIUM_VALUE,
      value3_5: MEDIUM_VALUE,
      value3_6: MEDIUM_VALUE,
      value3_7: MEDIUM_VALUE,
      value3_8: MEDIUM_VALUE,
      value3_9: MEDIUM_VALUE,
      value4_1: MEDIUM_VALUE,
      value4_2: MEDIUM_VALUE,
      value4_3: MEDIUM_VALUE,
      value4_4: MEDIUM_VALUE,
      value4_5: MEDIUM_VALUE,
      value4_6: MEDIUM_VALUE,
      value4_7: MEDIUM_VALUE,
      value4_8: MEDIUM_VALUE,
      value4_9: MEDIUM_VALUE,
      value5_1: MEDIUM_VALUE,
      value5_2: MEDIUM_VALUE,
      value5_3: MEDIUM_VALUE,
      value5_4: MEDIUM_VALUE,
      value5_5: MEDIUM_VALUE,
      value5_6: MEDIUM_VALUE,
      value5_7: MEDIUM_VALUE,
      value5_8: MEDIUM_VALUE,
      value5_9: MEDIUM_VALUE,
    },
    OperationId: "AttrOperationId",
    operation_Id: "Attroperation_Id",
    OperationName: "AttrOperationName",
    operation_Name: "Attroperation_Name",
    TraceId: "AttrTraceId",
    trace_id: "Attrtrace_id",
    traceId: "AttrtraceId",
    spanId: "spanId",
  },
}
